[package]
name = "unibot"
version = "0.1.0"
authors = ["notkild <notkild@gmail.com>"]

[lib]
name = "libunibot"

[dependencies]
error-chain = "0.8"
hyper = "0.10"
hyper-native-tls = "0.2"
log = "0.3"
log4rs = "0.5"
select = "0.3"
